# Site settings
author: Michael McCullough
title: CLI Portfolio Project
header-img: img/home-bg.png
email: michael.mccullough21@gmail.com
copyright_name: Michael McCullough
description: > # this means to ignore newlines until "baseurl:"
  Park Trails
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  McCullough21

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
